name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World! testing if it skips"
      - name: Now It is
        run: |
          date
      - name: Directory content
        run: |
          ls -l
