name: Deployment pipeline

env:
  PUSH_CONDITION: ${{ github.event_name == 'push' }}
  TAG_SKIP_CONDITION: ${{ contains(join(github.event.commits.*.message, ', '), '#skip') }}

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: npm run eslint -- --fix
      - run: npm run build
      - run: npm run test
      - run: npx playwright install --with-deps
      - run: 'npm run test:e2e'
      - name: Trigger deployment
        if: ${{ env.PUSH_CONDITION == 'true' }}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        if: ${{ env.PUSH_CONDITION == 'true' && env.TAG_SKIP_CONDITION == 'false' }}
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
